spring:
  application:
    name: artist-album-api
  
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Logging optimized for container
logging:
  level:
    root: INFO
    br.gov.seplag: INFO
    org.springframework: WARN
    org.hibernate: WARN

# MinIO Configuration (Docker)
minio:
  url: http://minio:9000
  external-url: http://localhost:9000
